name: Node.js CI

on:
  push:
    branches:
      - master
    tags: 
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      node-version: 19.x # See Node.js release schedule: https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node v${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'
      
      - run: yarn install --frozen-lockfile

      - name: Fetch next version
        uses: mathieudutour/github-tag-action@v6.1
        id: find_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          dry_run: true

      - name: Set package.json version to ${{ steps.find_version.outputs.new_tag }}
        run: >
          cp package.json tmp.json;
          jq -r '.version |= "${{ steps.find_version.outputs.new_version }}"' tmp.json > package.json;
          rm -rf tmp.json

      - name: Set manifest.json version to ${{ steps.find_version.outputs.new_tag }}
        run: >
          cp source/manifest.json tmp.json;
          jq -r '.version |= "${{ steps.find_version.outputs.new_version }}"' tmp.json > source/manifest.json;
          rm -rf tmp.json

      - run: yarn run lint

      - run: yarn run build

      - uses: actions/upload-artifact@master
        with:
          name: extensions
          path: extension/

  package:
    needs: build
    runs-on: ubuntu-latest
    env:
      node-version: 19.x # See Node.js release schedule: https://nodejs.org/en/about/releases/
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}

    steps:
      - uses: actions/download-artifact@master
        with:
          name: extensions
          path: extension/

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.1
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master

      - name: Create GitHub release tag ${{ steps.tag_version.outputs.new_tag }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: extension/chrome.zip, extension/edge.zip, extension/opera.zip, extension/firefox.xpi
